### ISSUE TITLE
Editing user role - An exception occured

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#109]
When editing a user role:

![image](https://cloud.githubusercontent.com/assets/8737709/16443707/8d65e608-3dda-11e6-9be9-2c78dbf17fa0.png)

![selection_2016062909 17 18](https://cloud.githubusercontent.com/assets/8737709/16443749/c93db372-3dda-11e6-823d-872d4e11b9a9.png)

**Comment by abyot** [comment]
Fixed.

**Comment by Aleglise** [comment]
@abyot you said

> One small note I suggest is - please let's pay special attention when dealing with category options, categories and category combos. We can't just add/remove category options to existing category which is linked to existing category combo. If we are to do this - please create a totally new category and category combination. 

So, how should MINAGRI manage the addition of new stakeholders?

**Comment by abyot** [comment]
This is a logical and what I would say a standard practice to follow.

Once data collection has started - based on a particular combination of dimensions - you can't just come and change the dimension. The problem is what to do with the previously collected data?

This does not mean it is impossible to add dimension. It is possible to add - but this needs to be for an altogether new dimension. If there is no data collected for an existing dimension - the safest way is to remove the dimension (with dimension I am referring to category combo) and recreate it.

Removing a dimension is a little complicated - again if data is already collected.

**Comment by Aleglise** [comment]
OK. How do you suggest to update Stakeholder list ?

Is there another option than to create 40 options for stakeholder category:
MINAGRI
RAB
NAEB
MINALOC
Earmarked
SPIU World Bank LWH
SPIU World Bank RSSP
SPIU World Bank FEEDER ROAD
SPIU World Bank RCSP
SPIU IFAD PASP
SPIU IFAD PRICE
SPIU IFAD KWAMP
SPIU ADB LISP
SPIU ADB PAIRB
SPIU MINAGRI FEEDER ROAD
SPIU MINAGRI G.G Buffet Fundation
SPIU MINAGRI I&C program
SPIU MINAGRI STRATEGIC RESERVE
Stakeholder 19
Stakeholder 20
...
Stakeholder 40

This option would be dirty and not flexible but like that, DHIS2 admin keep Stakeholder 19 to Stakeholder 40 to rename them when new stakeholder will come ?

**Comment by abyot** [comment]
That is a known intentional limitation in DHIS2. 

Updating stakeholder list should not be supported once you have started collecting data.

Instead of updating the existing stakeholder list. why not create a new stakeholder list?

You can before hand create placeholder options that you can rename later, but that is not a good solution.

**Comment by abyot** [comment]
I don't have a solution for this.

That is just how it is in DHIS 2. Once data collection has started, it is not possible to change category combo.
