### ISSUE TITLE
Baseline data entry and stakeholders list

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#50]
Baseline data is not related to any stakeholders as it is just a total from previous year, so it should be visible to every stakeholder.

Ex. Indicator 2.0.3.1 "Number and % of farmers with permanent access to crop advisory services (by gender)" which is collected by RAB/NAEB, MINAGRI and SPIU.

**Comment by abyot** [comment]
I am not really confident on this ... but what you could do is assign a stakeholder list only to target and progress data sets not to baseline data set. This could work as far as data entry is concerned.

For performance contract reporting, I will make changes so that it becomes possible to filter data based on stakeholder. Currently it is not possible to do this.

**Comment by Aleglise** [comment]
Each data set can have his own stakeholder list.

**Comment by Aleglise** [comment]
Let close it and wait for users feedback.
