### ISSUE TITLE
Data set not visible for addition during sub program creation

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#80]
When creatin the subprogram 2.1, I am able to add the Increased availability of technologies to increase the productivity, quality and resilience of food and export crops output:
![selection_2016061411 10 06](https://cloud.githubusercontent.com/assets/8737709/16037550/4e22a87e-3221-11e6-96bf-260d3c02bb83.png)

But not the Increased availability of technologies to increase the productivity, quality and resilience of food and export crops data set (whereas I should be able to add it too):
![selection_2016061411 10 28](https://cloud.githubusercontent.com/assets/8737709/16037558/536194bc-3221-11e6-8577-465c306e4599.png)

**Comment by Aleglise** [comment]
@neha 
Outputs Data sets are created according to subprograms.

Impact & Outcome Data sets should be created according to result Impact & Outcome

**Comment by arunimam** [comment]
@ Alex 

**Current Scenario**

1) All the datasets created in the application have following naming convention:
Sub program name   Level and    Periodicity for e.g Soil Conservation & Land Husbandry District Level Quarterly Dataset, in this Soil Conservation & Land Husbandry is the sub program name, level is district and Quarterly is the periodicity, if any indicator is being reported from multiple levels then the dataset name has all the levels, for e.g we have a dataset Agricultural Finance District/Sector level Annual Dataset so in this dataset the indicators are being reported from District and sector level both, hence the name

2) Neither of the datasets have mixed indicators means either a dataset has an Outcome indicator, either output indicator or Impact indicator. None of the dataset has a mix of outcome-ouput, output-impact, outcome-impact indicator

3) Also according to the indicator type dataset type is selected for e.g. we have an indicator Agricultural households with crop & livestock insurance which is of output type so the dataset type is also output

**Required Scenario**

4) Now according to clients requirement we need to rename the datasets like this
All the output datasets will be having sub programs in their dataset names for e.g Agricultural Finance District/Sector level Annual Dataset is assigned with  output type indicators hence it has the sub program name Agricultural Finance, same like current scenario

5) Whereas all the datasets with outcome & impact type will have their results name in their dataset name for e.g Annual value added of cultivated land per agricultural household is an Outcome type of indicator its dataset name will be Improved use of scarce land resources through sustainable intensification of crop and livestock production systems

If yes, then please confirm so that necessary action can be taken and datasets names can be changed
If no, then requesting you to explain with examples

**Comment by Aleglise** [comment]
I agree. Please create data sets.
