### ISSUE TITLE
Custom Periodicity

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#92]
Is it possible to set custom periodicity?

The National Institute of Statistics of Rwanda (NISR) conducts the annual Seasonal Agricultural Surveys (SAS) covering all three agricultural seasons in Rwanda:
·         Season A that starts in September and ends with February of the following year;

·         Season B that starts in March and ends with June of the same year; and

·         Season C that starts in July and ends in September of the same year

As this request is out of initial scope, priority is set to low.

**Comment by abyot** [comment]
No, custom period is not possible in DHIS2. The reason is - it will be tricky to do aggregation.

Do you have more information about the use case ? For example: what is collected, how often is data collected per season, what kind of report is expected.

If  we can model their use case as something like an event or survey that happens once - say for example between September and February - we could use Event Capture of DHIS2.

**Comment by Aleglise** [comment]
Thank you Abyot.

**Comment by Aleglise** [comment]
Abyot: It can be tracked through event and displayed in pivot table.
