### ISSUE TITLE
How get budget forecast per program and sub-program?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#97]

**Comment by abyot** [comment]
Budgets need to have forecast/execution dataset. In these datasets we need to create data elements where we store actual budget figures. 

The way this works is that we create one data element per sub-program. We haven't considered creating budget data element per program - this is because we are not sure (at least I do not remember getting a clear client need) whether (1) to sum sub-program budget and get program budget or (2) collect independently for program also.

In any case we have the solution whichever way it is decided.

If the approach is (1) then we can create get the total by creating data element groups (using those data elements that correspond the sub-programs making the program) and use this data element group as dimension in pivot table. By re-arranging the layout of the pivot it is possible to generate column / row total in the pivot table app.

If the approach is (2) - it is easy. just create one more budget data element per program and collect it.

One thing we need to keep in mind that budget data elements need to have "Project budget breakdown" category combination assigned to them so that we get something like the following:

![image](https://cloud.githubusercontent.com/assets/4967749/16229282/3f516a1a-37bc-11e6-8403-cfa399066fbe.png)

If we are interested in breaking down budgets by stakeholders like for example shown below

![image](https://cloud.githubusercontent.com/assets/4967749/16229331/72fadd2e-37bc-11e6-8236-dbe9b2f7b1c6.png)

we need to assign stakeholder list for our budget data sets. We also need to assign our forecast and execution budget data sets to our project.

The way budget is collected is just like standard data entry (at least for execution). The forecast is a little different - it is possible to do it like standard data entry. But it is recommended to do it using the Project definition UI. This way it is more coherent with project definition, its total budget. The forecast is  a breakdown of total budget. 

Clicking on any project gives context menu and this menu has UI to enter budget forecast.
